### ISSUE TITLE
Update released crate following added support for Android

### ISSUE THREAD

**Issue by ptosi** [rust-vmm/vmm-sys-util#163]
The released version the crate (v0.9.0)  breaks when targeting Android even though support was added in  #162; could it be upgraded?

**Comment by andreeaflorescu** [comment]
We need to do a new release of the crate to be able to fix this. Releases are not automatically done. This release is going to take some work since we haven't done one in a really long time. We can prioritize this next week in case the other code owners (CC: @sameo @jiangliu) don't have the time to work on this sooner than that.

**Comment by ptosi** [comment]
Sounds good; thanks for the update.

**Comment by andreeaflorescu** [comment]
We published v0.10.0, closing this.
