### ISSUE TITLE
Reason why real-time signals are  'vcpu signals'

### ISSUE THREAD

**Issue by iulianbarbu** [rust-vmm/vmm-sys-util#53]
I am looking in the `signal.rs` and I do not understand why real-time signals are `for_vcpu` signals, knowing that `register_signal_handler` function [0] receives the argument `for_vcpu`, which is registering a real-time signal with a signum equal to `SIGRTMIN + num`, when `for_vcpu` is `true`.

Why is semantically different how standard signals and real-time signals handlers are registered?
Couldn't we change the `for_vcpu` parameter name, of `register_signal_handler` function, to `is_rtsig`, lets say, and not lose any information about how the function should be used?

[0] https://github.com/rust-vmm/vmm-sys-util/blob/472614c3a21231f6a0c3696fab83fb34d6592ade/src/signal.rs#L191

**Comment by acatangiu** [comment]
@crate-code-owners, is there a reason why signal registration is differentiated between `vcpu`-thread and non-`vcpu`-thread?

Why are `vcpu` signal numbers off-setted under the hood to land in the `SIGRTMIN` and `SIGRTMAX` range.

I'd like this interface to expose a clean design with no unnecessary under-the-hood magic. Users of the crate should have full control over which signals are being actually used.

**Comment by andreeaflorescu** [comment]
The reason is probably because that's how we have it in Firecracker. In Firecracker we use "vcpu" instead of "real time" as well. This should be fixed.

Now, talking about the fix, most of the times having a boolean as a parameter is not a good sign. It means that your function is not doing one thing and one thing only. So instead of changing `for_vcpu` to `is_rtsig` how about we have two functions instead:
- register_signal_handler
- register_rt_signal_handler. This function would have an extra check that the signal is indeed realtime and then just call into `register_signal_handler`.

CC: @sameo

**Comment by aghecenco** [comment]
> The reason is probably because that's how we have it in Firecracker. In Firecracker we use "vcpu" instead of "real time" as well. This should be fixed.

True. Firecracker differentiates between signals that make sense to vCPU threads (`SIGRTMIN` to `SIGRTMAX`) and signals that make sense to the process (e.g. `SIGSYS`, `SIGSEGV` etc).
We used to have a single `register` function and did the validation *for vcpu* vs *for process* "behind the scenes". That changed in https://github.com/firecracker-microvm/firecracker/commit/6fd470ddd072113cff56cbe93e8593eafa0afdf3 when we decided against exposing a unified API that does 2 different things.

> Now, talking about the fix, most of the times having a boolean as a parameter is not a good sign. It means that your function is not doing one thing and one thing only. So instead of changing `for_vcpu` to `is_rtsig` how about we have two functions instead:
> 
>     * register_signal_handler
> 
>     * register_rt_signal_handler. This function would have an extra check that the signal is indeed realtime and then just call into `register_signal_handler`.
> 

Makes sense to me, with the addendum that as a new contibutor I'd have no idea why realtime signals are specials. We should make it obvious that realtime signals are for the vCPU threads.

**Comment by acatangiu** [comment]
> We should make it obvious that realtime signals are for the vCPU threads.

But why should we impose/force that design?

Signal handlers are at the full process level. There is no way to register a specific handler on a specific thread (only signal delivery can be done per-thread).
I would just keep a single `register_signal_handler` function and the user can build any system he wants.

**Comment by aghecenco** [comment]
I think the original idea was to make it easy to kick the vcpu out of its run loop so that the kicker doesn't need to do the awkward math of `thread.kill(SIGRTMIN + delta)`. Either the kicker or the signal handler need to do that math, so `SIGRTMIN + something` is bound to end up somewhere. I don't feel strongly about either option of placing them. I nonetheless stick to the idea of informing via comments that RT signals have something to do with vcpus.
